# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='will_be_active',
            field=models.DateField(blank=True, null=True),
        ),
    ]
