# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180320_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='final_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='shop.User'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='bit', to='shop.User'),
        ),
    ]
