# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180320_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='buyer_complete',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vendor_complete',
        ),
    ]
