# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180321_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='buyer_complete',
            field=models.BooleanField(default=False, verbose_name='Transakce Proběhla'),
        ),
        migrations.AddField(
            model_name='offer',
            name='vendor_complete',
            field=models.BooleanField(default=False, verbose_name='Transakce Proběhla'),
        ),
    ]
