# Generated by Django 2.0.3 on 2018-03-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180321_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='book',
            field=models.ForeignKey(on_delete='cascade', to='shop.Book', verbose_name='kniha'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='final_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', related_name='purchase', to='shop.User'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='vendor',
            field=models.ForeignKey(on_delete='cascade', related_name='offer', to='shop.User'),
        ),
    ]
